package com.study.september.week4;

import java.util.Arrays;

/**
 * Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 *
 */
public class Solution24 {
    public char findTheDifference_5ms(String s, String t) {

        char[] sChar = s.toCharArray();
        char[] tChar = t.toCharArray();

        Arrays.sort(sChar);
        Arrays.sort(tChar);

        for(int i = 0; i < s.length(); i ++){
            if(sChar[i] != tChar[i]) return tChar[i];
        }

        return tChar[tChar.length - 1];

    }

    public char findTheDifference(String s, String t) {
        char[] sChar = s.toCharArray();
        char[] tChar = t.toCharArray();

        int sumS = 0, sumT = 0;

        for(int i = 0; i < s.length(); i ++){
            sumS += sChar[i] - 'a';
            sumT += tChar[i] - 'a';
        }

        sumT += tChar[tChar.length - 1] - 'a';

        return (char) (sumT - sumS + 'a');

    }
}
